apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gbcfullstack.azurecr.io/backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: ALCHEMY_API_KEY
          valueFrom:
            configMapKeyRef:
              name: alchemy-config
              key: ALCHEMY_API_KEY
      imagePullSecrets:
      - name: acr-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gbcfullstack.azurecr.io/frontend:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-credentials
